### ISSUE TITLE
Naming convention issue

### ISSUE THREAD

**Issue by tommymb** [tommymb/grid-layout#1]
@muxlowc

Trying to submit this old one that I realized I never finished because it gives me an error message about the naming conventions of the images being used. 

I thought it was because of the capitals, but as you can see from the "temple_of_artemis" file, I changed it to lowercase but the error message still remained. I also thought it could have been the underscores but after a couple times trying to change those it seems when I do the image disappears from my webpage. 

Feels like there's a simple solution here I just can't figure it out without messing up my website. All my other checks are met, its just this naming issue. 
![Screen Shot 2020-04-16 at 5 31 35 PM](https://user-images.githubusercontent.com/43139261/79509278-31fdd080-8009-11ea-89f1-7053d062a084.png)

**Comment by muxlowc** [comment]
@tommymb  try using only dashes, instead of underscores - I think that should do it
